language: python

python:
- 3.6
- 3.7

dist: xenial

sudo: true

services:
- mysql
addons:
  apt_packages:
  - libcups2-dev
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install flake8
- pip install coveralls
- pip install -e .
- pip install -r requirements.txt
before_script:
- flake8 ambition_metadata_rules
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=ambition_metadata_rules manage.py test
after_success:
- coveralls
